# Generated by Django 5.0.14 on 2026-01-13 07:40

import ecommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_alter_category_options_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ecommerce.models.product_image_upload_to,
            ),
        ),
    ]
