# Generated by Django 5.0.14 on 2026-01-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(default="EUR", max_length=3),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="", max_length=255),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="ecommerce_c_slug_53629f_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active"], name="ecommerce_c_is_acti_1e5a3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["position"], name="ecommerce_c_positio_5da1cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="ecommerce_p_slug_b8decd_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active"], name="ecommerce_p_is_acti_46ccda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["position"], name="ecommerce_p_positio_997e89_idx"
            ),
        ),
    ]
